export const apis = {
  auth_login: '/login',
  current_user: '/current-user',
  post_document: '/documents',
  get_documents: '/documents',
  get_document_by_uuid: '/documents/:id',
  get_document_by_id: '/documents/:id',
  get_document_distinct_product_name: '/documents-product-name',
  approve_document: '/documents-approve',
  reject_document: '/documents-reject',
  monitoring_document: '/documents-monitoring',
  tracking_document: '/documents-tracker/:name',
  get_notifications: '/notifications',
  read_all_notifications: '/notifications/read-all',
  user_registration_apply: '/user-registrations/apply',
}
